### ISSUE TITLE
Update RBAC to meet best practice requirements(using fine-grained permission)

### ISSUE THREAD

**Issue by xuezhaojun** [stolostron/hypershift-addon-operator#33]
Right now,  we are using a lot of verb`*` in https://github.com/stolostron/hypershift-addon-operator/blob/main/pkg/manager/manifests/templates/clusterrole.yaml, we want more fine-grained permission.

It would be easier with the e2e test done.

This is a good first issue.

**Comment by rokej** [comment]
https://issues.redhat.com/browse/ACM-1956

**Comment by philipwu08** [comment]
PR: 
https://github.com/stolostron/hypershift-addon-operator/pull/113
https://github.com/stolostron/backplane-operator/pull/346
