### ISSUE TITLE
aws platform detection incorrectly based on the presence of hypershift-operator-oidc-provider-s3-credentials secret

### ISSUE THREAD

**Issue by jharting** [stolostron/hypershift-addon-operator#84]
In https://github.com/stolostron/hypershift-addon-operator/blob/47e349c864b6d4be515f20dde94b8d26a9c6bb73/pkg/install/hypershift.go#L160-L167 the detection of the aws platform is based on the presence of the `hypershift-operator-oidc-provider-s3-credentials` secret.

This is incorrect because the oidc s3 credentials are optional for hypershift even when used on the aws platform is used. In such a scenario, things work as follows:

- a provisioner creates the oidc documents for a new cluster upfront
- when creating a new HostedCluster, the provisioner communicates the location of the oidc documents to hypershift via the `issuerURL` field in the HostedCluster resource
- as the oidc documents are created by the provisioner, hypershift does not need to create them (and thus does not need the credentials)

As a result, when the oidc provider credentials are not provided then other valid aws configuration (specifically PrivateLink credentials https://github.com/stolostron/hypershift-addon-operator/blob/47e349c864b6d4be515f20dde94b8d26a9c6bb73/pkg/install/hypershift.go#L209-L225) are ignored.

**Comment by rokej** [comment]
https://issues.redhat.com/browse/ACM-1851

**Comment by o-farag** [comment]
Resolved with https://github.com/stolostron/hypershift-addon-operator/pull/189
